export const DASHBOARD_HOME_MENU = "DASHBOARD_HOME_MENU";
export const DASHBOARD_QUESTIONS_MENU = "DASHBOARD_QUESTIONS_MENU";
export const DASHBOARD_CATEGORIES_MENU = "DASHBOARD_CATEGORIES_MENU";
export const DASHBOARD_EXAMS_MENU = "DASHBOARD_EXAMS_MENU";

export const TOOLTIP_POSITION = "right"